package com.streamwork.ch02.job;

import com.streamwork.ch02.api.Event;
import com.streamwork.ch02.api.Source;
import com.streamwork.ch02.vo.RandomVehicleEventCreator;

import java.util.List;

public class AutoGeneratedSensorReader extends Source {
    private final RandomVehicleEventCreator randomVehicleEventCreator = new RandomVehicleEventCreator();

    public AutoGeneratedSensorReader(String name) {
        super(name);
    }

    @Override
    public void getEvents(List<Event> eventCollector) throws InterruptedException {
        Thread.sleep(1000);
        VehicleEvent vehicleEvent = createEventRandomly(eventCollector);
        printInfo(vehicleEvent);
    }

    private VehicleEvent createEventRandomly(List<Event> eventCollector) {
        VehicleEvent vehicleEvent = randomVehicleEventCreator.create();
        eventCollector.add(vehicleEvent);
        return vehicleEvent;
    }

    private static void printInfo(VehicleEvent vehicleEvent) {
        System.out.println();  // An empty line before logging new events
        System.out.println("SensorReader --> " + vehicleEvent.getData());
    }
}
