package com.streamwork.ch02.job;

import com.streamwork.ch02.api.Event;
import com.streamwork.ch02.api.Source;
import com.streamwork.ch02.vo.RandomVehicleNameCreator;

import java.util.List;

public class AutoGeneratedSensorReader extends Source {
    private final RandomVehicleNameCreator randomVehicleNameCreator = new RandomVehicleNameCreator();

    public AutoGeneratedSensorReader(String name) {
        super(name);
    }

    @Override
    public void getEvents(List<Event> eventCollector) throws InterruptedException {
        Thread.sleep(1000);
        String vehicleName = randomVehicleNameCreator.create();
        eventCollector.add(new VehicleEvent(vehicleName));
        System.out.println();  // An empty line before logging new events
        System.out.println("SensorReader --> " + vehicleName);
    }
}
