package com.streamwork.ch02.job;

import com.streamwork.ch02.api.Job;
import com.streamwork.ch02.api.Stream;
import com.streamwork.ch02.engine.JobStarter;

public class VehicleCountJob {

  public static void main(String[] args) {
    Job job = new Job("vehicle_count");

//    Stream bridgeStream = job.addSource(new SensorReader("sensor-reader", 9990));
    Stream bridgeStream = job.addSource(new AutoGeneratedSensorReader("auto-generated-sensor-reader"));

    // applyOperator 메서드는 새로운 Stream을 만들어내기 때문에 만들어진 Stream에 Operator를 새로 등록해야만 작업이 이어짐.
    Stream counterAppliedStream = bridgeStream.applyOperator(new VehicleCounter("vehicle-counter"));
    counterAppliedStream.applyOperator(new VehicleResultPrinter("vehicle-result-printer"));

    System.out.println("This is a streaming job that counts vehicles in real time. " +
        "Please enter vehicle types like 'car' and 'truck' in the input terminal " +
        "and look at the output");
    JobStarter starter = new JobStarter(job);
    starter.start();
  }
}
